import Head from "next/head";
import Carousel from "./components/Carousel";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import Image from "next/image";
import HR from "./../Images/HRM-icon.png";
import ICT from "./../Images/ICT-icon2.png";
import FM from "./../Images/FM-icon.png";
import PL from "./../Images/PL-icon2.png";
import PM from "./../Images/PM-icon.png";
import UNDP from "./../Images/UNDP-logo.png";
import INTERSOS from "./../Images/INTERSOS-logo.png";
import WELTHUNGER from "./../Images/welthungerhilfe-logo.png";
import NTA from "./../Images/NTA-LOGO.png";
import HAPN from "./../Images/HAPN-LOGO.png";
import SAVANA from "./../Images/SAVANA-LOGO.png";
import Link from "next/link";
import { BsArrowRightShort } from "react-icons/bs";
import consultants from "./../public/consultants-small.png";
import { ParallaxBannerLayer, ParallaxBanner } from "react-scroll-parallax";

export default function Home() {
  return (
    <div className="text-lg">
      <Head>
        <title>Tali Consultancy</title>
        <meta name="description" content="Generated by Maui Inc" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="relative shadow-lg">
        <Carousel />
        <div className="absolute top-0 w-full z-10">
          <Navbar />
        </div>
      </div>
      <div id="start-home" className="flex font-bold justify-center mt-16 mb-8 text-2xl text-gray-500">
        WHAT WE DO
      </div>
      <div className="flex flex-col mb-16">
        <div className="flex pl-10 my-3">
          <div>
            <Image
              src={HR}
              height={80}
              width={80}
              alt="Human Resource management"
            />
          </div>
          <div className="flex flex-col w-2/3 pr-3 pl-1">
            <div className="text-teal-500 text-xl font-semibold">
              Human Resource Management
            </div>
            <div>
              Maximize the value of your most valuable
              asset - Your employees.
            </div>
            <Link
              className="text-teal-600 flex items-center"
              href="/services/#human-resource-management"
            >
              Read more{" "}
              <BsArrowRightShort className="text-2xl font-semibold pt-1" />
            </Link>
          </div>
        </div>
        <div className="flex pl-10 my-3">
          <div>
            <Image
              src={ICT}
              height={80}
              width={80}
              alt="Strategic ICT consulting"
            />
          </div>
          <div className="flex flex-col w-2/3 pr-3 pl-1">
            <div className="text-teal-500 text-xl font-semibold mb-2">
              Strategic ICT Consulting
            </div>
            <div>
              Identify and capitalize on key information and communication
              technology opportunities such as vendor
              management, security and compliance, cloud services and more.
            </div>
            <Link
              className="text-teal-600 flex items-center"
              href="/services/#strategic-ICT-consulting"
            >
              Read more{" "}
              <BsArrowRightShort className="text-2xl font-semibold pt-1" />
            </Link>
          </div>
        </div>
        <div className="flex pl-10 my-3">
          <div>
            <Image
              src={FM}
              height={80}
              width={80}
              alt="Financial and Grants Management"
            />
          </div>
          <div className="flex flex-col w-2/3 pr-3 pl-1">
            <div className="text-teal-500 text-xl font-semibold mb-2">
              Financial and Grants Management
            </div>
            <div>
              Ensure financial stability and sustainability through effective financial controls, budgeting, forecasting, performance and more.
            </div>
            <Link
              className="text-teal-600 flex items-center"
              href="/services/#financial-grants-and-management"
            >
              Read more{" "}
              <BsArrowRightShort className="text-2xl font-semibold pt-1" />
            </Link>
          </div>
        </div>
        <div className="flex pl-10 my-3">
          <div>
            <Image
              src={PL}
              height={80}
              width={80}
              alt="Procurement and Logistics"
            />
          </div>
          <div className="flex flex-col w-2/3 pr-3 pl-1">
            <div className="text-teal-500 text-xl font-semibold mb-2">
              Procurement and Logistics
            </div>
            <div>
              Optimize supply chain management and logistics processes through Procurement Transformation, Business Process Re-engineering, stock control and more.
            </div>
            <Link className="text-teal-600 flex items-center" href="/services/#procurement-and-logistics">
              Read more{" "}
              <BsArrowRightShort className="text-2xl font-semibold pt-1" />
            </Link>
          </div>
        </div>
        <div className="flex pl-10 my-3">
          <div>
            <Image
              src={PM}
              height={80}
              width={80}
              alt="Performance management"
            />
          </div>
          <div className="flex flex-col w-2/3 pr-3 pl-1">
            <div className="text-teal-500 text-xl font-semibold mb-2">
              Project Management
            </div>
            <div>
              Employ advanced methodology and technologies to ensure optimal project delivery with Monitoring and Evaluation (M&E), Community Development, Capacity Building and more.
            </div>
            <Link
              className="text-teal-600 flex items-center"
              href="/services/#project-management"
            >
              Read more{" "}
              <BsArrowRightShort className="text-2xl font-semibold pt-1" />
            </Link>
          </div>
        </div>
      </div>
      <div className="h-60 w-full flex relative">
        <div className="bg-teal-900 absolute h-full w-full z-10 opacity-60  items-center flex justify-center"><div className="text-gray-50 text-5xl absolute z-10"><span className="font-semibold">5+</span> countries</div></div>
        <ParallaxBanner style={{ position: "relative" }}>
          <ParallaxBannerLayer speed={-15}>
            <Image src={consultants} alt="consultants" fill />
          </ParallaxBannerLayer>
        </ParallaxBanner>
      </div>
      <div className="mb-12 mt-20">
        <div className="text-2xl justify-center flex font-bold text-gray-500">
          SOME OF OUR CLIENTS
        </div>
      </div>
      <div className="flex my-10 flex-col">
        <div className="flex w-full mb-8">
          <div className="w-1/2 flex justify-center">
            <div className="border-2 border-teal-500 p-3 flex items-center h-40 w-40 justify-center">
              <Image src={UNDP} alt="UNDP" height={120} width={120} />
            </div>
          </div>
          <div className="w-1/2 flex justify-center">
            <div className="border-2 border-teal-500 p-3 items-center flex h-40 w-40 justify-center">
              <Image src={INTERSOS} alt="INTERSOS" height={120} width={120} />
            </div>
          </div>
        </div>
        <div className="flex w-full mb-8">
          <div className="w-1/2 flex justify-center">
            <div className="border-2 border-teal-500 p-3 flex items-center h-40 w-40 justify-center">
              <Image
                src={WELTHUNGER}
                alt="WELT-HUNGER-HILFE"
                height={120}
                width={120}
              />
            </div>
          </div>
          <div className="w-1/2 flex justify-center">
            <div className="flex border-2 border-teal-500 p-3 items-center h-40 w-40 justify-center">
              <Image src={NTA} alt="NTA" height={120} width={120} />
            </div>
          </div>
        </div>
        <div className="flex w-full mb-8">
          <div className="w-1/2 flex justify-center">
            <div className="border-2 border-teal-500 p-3 flex items-center h-40 w-40 justify-center">
              <Image
                src={HAPN}
                alt="Horn of Africa Peace Network"
                height={120}
                width={120}
              />
            </div>
          </div>
          <div className="w-1/2 flex justify-center">
            <div className="flex border-2 border-teal-500 p-3 items-center h-40 w-40 justify-center">
              <Image src={SAVANA} alt="UNDP" height={120} width={120} />
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
}
